# With this dockerfile, react app access env at build time, so it can not be changed at runtime.
# As a result, the react app can not access the backend api at runtime.
FROM node:14

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .
COPY public ./public
COPY src ./src

ENV REACT_APP_API_URL=http://localhost:80

RUN npm run build

FROM nginx:alpine
COPY --from=0 /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
