FROM python:3.9

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV MONGO_URL=mongodb://mongo:27017

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
