name: Monitor Deployment Workflow
on:
  workflow_run:
    workflows: ["Build and Deploy Workflow"]
    types:
      - completed

permissions:
  id-token: write
  contents: read
  issues: write
  actions: read

jobs:
    create-issue-if-failed:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'failure'}}
      env:
        GITHUB_TOKEN: ${{ github.token }}
      steps:
        - name: Create issue if workflow run failed
          run: |
            echo "Creating issue for failed workflow run..."
            issueTitle="Run ${{ github.event.workflow_run.id }} failed for workflow ${{ github.event.workflow_run.name }}"
            workflowFailureLog=$(gh run view ${{ github.event.workflow_run.id }} --log-failed)
            issueBody="The workflow run failure log:\n$workflowFailureLog"
            echo "$issueBody"
            gh issue create --title "$issueTitle" --body "$issueBody" --repo ${{ github.event.repository.full_name }} --assignee "Copilot"
